### ISSUE TITLE
Settings do not save in DNN 9.01+

### ISSUE THREAD

**Issue by shanewalker1595** [davidjrh/dnn.azureadprovider#12] opened 2018-04-05 20:36 UTC
When configuring settings in DNN 9.01+, the settings will not save. Manually creating them in the Database works though.

Status Code: 404
URL: /API/personaBar/AzureAD/UpdateSettings

**Comment by davidjrh** [comment] 2018-05-18 18:34
Hi @shanewalker1595, I'm running a 9.1.1 and can't reproduce the issue. Can you confirm this is still a problem?

**Comment by shanewalker1595** [comment] 2018-06-17 11:18
The issue seems to be resolved in DNN 9.1.1

**Comment by davidjrh** [comment] 2018-12-05 20:32
Ok, closing the issue

**Closed by davidjrh** 2018-12-05 20:32 UTC
