### ISSUE TITLE
Problem after update AD password

### ISSUE THREAD

**Issue by rodsmr** [davidjrh/dnn.azureadprovider#46] opened 2021-04-19 14:38 UTC
**Environment**

- DNN 9.9.0
- DNN Azure AD Provider 4.0.4
- Windows Server 2012 R2

**Problem**
I've update Azure Active Directory AAD password few days ago; after this change, I try to login my site and I've got the attached error
![ErroreAAD](https://user-images.githubusercontent.com/17640209/115253872-1aca5500-a12d-11eb-9488-be374c77df21.jpg)
If I discard the save user/pw and try new value (same email but different PW), I can login

1. Is it normally?
2. Is it depend on AAD config?
3. How to avoid it?

Thanks for the support, best regards

**Comment by rodsmr** [comment] 2021-07-20 12:41
I need to reopen this issue. Today an user updates its AAD password and it has the same problem

**Comment by shanewalker1595** [comment] 2021-07-20 12:44
@rodsmr , does the user have a Microsoft LIVE account with the same credentials as their AAD account?

**Comment by rodsmr** [comment] 2021-07-20 12:46
> @rodsmr , does the user have a Microsoft LIVE account with the same credentials as their AAD account?

I suppose yes (but I really dont know). Is there a way to debug?

**Comment by swalker1595** [comment] 2021-07-20 12:52
I'm not sure if there is a way to debug but we have had instances (not specific to DNN) where users had both a Personal Microsoft Live Account and an AAD Account with the same credentials. When this happens, I have seen instances where they will be redirected to https://login.live.com/ to login instead of https://login.microsoftonline.com/

If the user is logging into login.live.com instead of login.microsoft.com, you will get the error message you sent. Just one thought.

**Comment by rodsmr** [comment] 2021-07-20 12:55
@swalker1595 thanks. Can I force to use https://login.microsoftonline.com/ instead of https://login.live.com/ ?

**Comment by swalker1595** [comment] 2021-07-20 12:55
In fact, I was just able to recreate your exact issue by logging into our DNN tenant with my personal (Non-AAD) credentials:

![image](https://user-images.githubusercontent.com/35071216/126327774-0df5ec5b-0e09-4171-a4a0-18772bf162e2.png)

**Comment by swalker1595** [comment] 2021-07-20 13:00
I don't think there's any way to prevent this as it's Microsoft's intended behavior to redirect users to login.live.com

I hate linking to external sites but here's some documentation I found:
https://stackoverflow.com/questions/37245600/how-to-prevent-redirect-from-login-microsoftonline-com-to-login-live-com-while-u
https://docs.microsoft.com/en-us/answers/questions/34806/azure-ad-404-error-when-login-with-microsoft-accou.html
https://answers.microsoft.com/en-us/outlook_com/forum/all/loginmicrosoftonlinecom-redirecting-to/34fc19c7-6523-4a0f-b210-7c26b13c8316

**Comment by rodsmr** [comment] 2021-07-20 13:14
@swalker1595 thank you very much, I read your docs!

**Comment by rodsmr** [comment] 2021-07-30 08:22
Hi @swalker1595 
From [Microsoft OAuth 2.0 doc](**https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow**) , I modify the _AzureClient.cs_ code to add **new QueryParameter("prompt", "login")** at _Authorize() method_ 

I think this configuration can be choose by user during configuration. @davidjrh what do you think about my idea?

**Comment by davidjrh** [comment] 2022-11-03 19:23
Fixed on PR #69 

Thanks @alendv for the contribution.

**Closed by davidjrh** 2022-11-03 19:23 UTC
Labels: enhancement
